import { da } from "@/content/da";
import { soonHref } from "@/content/site";

export const en = {
  seo: {
    title: "Martial arts in Aalborg | Aalborg Martial Arts",
    description:
      "Kickboxing, Muay Thai, boxing and MMA at Aalborg Martial Arts in Nordkraft. From your first session to the fight team and national team. Kids, fitness and fighters. Same club.",
    keywords: [
      "martial arts Aalborg",
      "kickboxing Aalborg",
      "Muay Thai Aalborg",
      "boxing Aalborg",
      "MMA Aalborg",
      "fight team Aalborg",
      "kickboxing national team",
      "K1 Aalborg",
      "beginner martial arts Aalborg",
      "advanced martial arts Aalborg",
      "Kick'n Burn Aalborg",
      "kids martial arts Aalborg",
      "Aalborg Martial Arts",
      "AMA Nordkraft",
      "martial arts Nordkraft",
    ],
  },
  ui: {
    login: "Log in",
    loginMember: "Log in as a member →",
    menu: "Menu",
    close: "Close",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    mainNav: "Main menu",
    mobileNav: "Mobile menu",
    play: "Play",
    pause: "Pause",
    closeVideo: "Close video",
    seek: "Seek in the video",
    mute: "Mute",
    unmute: "Unmute",
    playWithSound: "Play video with sound",
    language: "Language",
    theme: "Change theme",
    themeNow: "Change theme. Now",
    themeTitle: "Switch between dark and light",
    dark: "Dark",
    light: "Light",
    system: "System",
    today: "today",
    pickDay: "Pick a day",
    facebook: "Facebook",
    instagram: "Instagram",
    maps: "Google Maps",
    nordkraftAlt: "Nordkraft in Aalborg, where Aalborg Martial Arts trains",
  },
  comingSoon: {
    eyebrow: "Coming soon",
    watermark: "Soon",
    title: "That page is on the way",
    topicLead: "is on the way.",
    body: "We are finishing the class and club pages. Until then you can book your first session or keep reading on the homepage.",
    home: "Back to the homepage",
    topics: {
      begynder: "Adult beginners",
      barn: "Kids and youth",
      kicknburn: "Kick'n Burn",
      kamp: "Fight team",
      sponsorer: "Sponsors",
      ok: "OK",
      axon: "Axon",
      igniz: "Igniz",
      portservice: "Portservice Nord",
    },
  },
  site: {
    tagline:
      "You do not need to be fit or have gear. If you are new, we look after you and get you involved, even when the class is not only beginners.",
    footerBlurb:
      "Kickboxing, Muay Thai, boxing, MMA and Kick'n Burn in Nordkraft, Aalborg.",
  },
  megaNav: [
    {
      id: "hold",
      label: "Classes",
      href: "/#hold",
      items: [
        {
          icon: "user" as const,
          label: "Adult beginners",
          hint: "Kickboxing, Muay Thai, boxing and MMA",
          href: soonHref("begynder"),
          image: "/media/punch-pads.jpg",
        },
        {
          icon: "users" as const,
          label: "Kids and youth",
          hint: "Ages 7-10 and 11-17",
          href: soonHref("barn"),
          image: "/media/sparring.jpg",
        },
        {
          icon: "flame" as const,
          label: "Kick'n Burn",
          hint: "Fitness. Almost no contact.",
          href: soonHref("kicknburn"),
          image: "/media/fairtex.jpg",
        },
        {
          icon: "trophy" as const,
          label: "Fight team",
          hint: "Advanced and competitions. Promotion by agreement.",
          href: soonHref("kamp"),
          image: "/media/kick-ring.jpg",
        },
      ],
    },
    {
      id: "start",
      label: "Get started",
      href: "/#tryghed",
      items: [
        {
          icon: "steps" as const,
          label: "First session",
          hint: "Clothes, water and four steps",
          href: "/#proeve",
          image: "/media/guard.jpg",
        },
        {
          icon: "help" as const,
          label: "FAQ",
          hint: "Booking, classes and gear",
          href: "/#faq",
          image: "/media/punch-pads.jpg",
        },
        {
          icon: "tag" as const,
          label: "Prices",
          hint: "49, 99 or 249 DKK a month",
          href: "/#priser",
          image: "/media/hero-still.jpg",
        },
        {
          icon: "users" as const,
          label: "Members",
          hint: "What they say about the club",
          href: "/#stemmer",
          image: "/media/kristoffer-poster.jpg",
        },
      ],
    },
    {
      id: "tider",
      label: "Times",
      href: "/#tider",
      items: [
        {
          icon: "calendar" as const,
          label: "Weekly schedule",
          hint: "See the next classes and book a spot",
          href: "/#tider",
          image: "/media/sparring.jpg",
        },
      ],
    },
    {
      id: "klubben",
      label: "The club",
      href: "/#om",
      items: [
        {
          icon: "pin" as const,
          label: "Find us",
          hint: "Nordkraft, Aalborg",
          href: "/#om",
          image: "/media/nordkraft.png",
        },
        {
          icon: "medal" as const,
          label: "Fighters",
          hint: "National team and fight team",
          href: "/#kaempere",
          image: "/media/kick-ring.jpg",
        },
        {
          icon: "handshake" as const,
          label: "Sponsors",
          hint: "Partners and become a sponsor",
          href: soonHref("sponsorer"),
          image: "/media/nav-club.jpg",
        },
      ],
    },
  ],
  hero: {
    eyebrow: "Nordkraft · Aalborg",
    title: "Come as you are",
    titleAccent: "At your pace",
    cta: "Book first session",
    ctaShort: "First session",
    secondary: "How it works",
    proof: "249 DKK a month. No contract. Gear to borrow.",
    rating: "4.9",
    ratingMeta: "14 reviews on Google",
    clips: [
      {
        src: "/media/kristoffer.mp4",
        title: "Training at Aalborg Martial Arts in Nordkraft",
      },
      {
        src: "/media/hero-clip-a.mp4",
        title: "Martial arts training at Aalborg Martial Arts",
      },
    ],
  },
  ticker: [
    "Kickboxing",
    "Muay Thai",
    "Boxing",
    "MMA",
    "Kick'n Burn",
    "Kids & youth",
    "Fight team",
    "Open Gym",
  ],
  pricing: {
    eyebrow: "Fees",
    title: "Membership",
    perMonth: "DKK / month",
    perMonthShort: "DKK / mo",
    trialLine: "You can borrow gear for the first sessions, and there is no contract.",
    offerDescription: "Unlimited training in the {age} age group. No contract.",
    included: [
      "One fee covers all training in your age group",
      "No extra charge for more classes",
      "You can borrow gear until you have bought your own",
      "The first 14 days have no contract, if you want to try the gym first",
      "Discount codes for your own gear and club kit",
    ],
    tiers: [
      { id: "senior", label: "Senior", age: "18+" },
      { id: "junior", label: "Junior", age: "11-17" },
      { id: "barn", label: "Kids", age: "7-10" },
    ],
  },
  barriers: {
    eyebrow: "Before you start",
    title: "What most people wonder",
    lead: "It is normal to worry about getting hit, looking silly or turning up without knowing what to do. Here is how it actually works with us.",
    items: [
      {
        id: "skade",
        fear: "I am going to get smashed",
        answer:
          "You train at the level your partner is at. On the beginner classes we work with technique, pads and bags, not fighting. At Kick'n Burn there is almost no contact. You might get a bruise. You will not get run over.",
      },
      {
        id: "form",
        fear: "I am in too bad shape",
        answer:
          "You do not need to be fit before you start. That is part of what the training gives you. We have members of all ages, and you train to your ability. It is never too late.",
      },
      {
        id: "passe",
        fear: "I will not fit in",
        answer:
          "Everyone in the gym was new once. If you are new, we look after you and get you involved, even when the class is not only beginners. Classes are for women and men, and we would like more women to join.",
      },
      {
        id: "kamp",
        fear: "I will have to fight",
        answer:
          "Most people train to get fit and never step into a ring. The fight team is a choice, when you and the coach agree you are ready. You decide how far you want to go.",
      },
      {
        id: "start",
        fear: "I do not know how to start",
        answer:
          "You book a time and turn up. How it works is in Four steps further down the page.",
      },
    ],
  },
  doors: {
    eyebrow: "Classes",
    title: "Where do you want to start?",
    lead: "You do not need to know every class name. Pick the path that fits, and we find the level together.",
    items: [
      {
        id: "begynder",
        title: "Adult beginners",
        description:
          "Kickboxing, Muay Thai, boxing or MMA. You start gently, even if you have never tried it.",
        href: soonHref("begynder"),
        image: "/media/punch-pads.jpg",
      },
      {
        id: "barn",
        title: "Kids and youth",
        description: "Classes for ages 7-10 and 11-17. Technique, play and a safe community.",
        href: soonHref("barn"),
        image: "/media/sparring.jpg",
      },
      {
        id: "kicknburn",
        title: "Kick'n Burn",
        description:
          "Fitness and strength with martial arts drills, and almost no contact.",
        href: soonHref("kicknburn"),
        image: "/media/fairtex.jpg",
      },
      {
        id: "kamp",
        title: "Fight team",
        description:
          "For you who already train and want to compete. Promotion happens by agreement with the coach.",
        href: soonHref("kamp"),
        image: "/media/kick-ring.jpg",
      },
    ],
  },
  startSteps: {
    eyebrow: "First session",
    title: "Four steps",
    items: [
      {
        step: 1,
        title: "Bring clothes and water",
        description:
          "Training clothes and a bottle of water are enough. You do not need to buy anything before you have tried it.",
      },
      {
        step: 2,
        title: "Borrow gear in the gym",
        description:
          "We have gloves and shin guards you can borrow, so you can turn up without buying equipment.",
      },
      {
        step: 3,
        title: "The coach meets you",
        description:
          "Say it is your first time. We look after you and get you into the session, even when the class is not only newcomers.",
      },
      {
        step: 4,
        title: "Decide afterwards",
        description:
          "If it feels right, you can join as a child, junior or senior. If not, you stop. There is no contract.",
      },
    ],
  },
  voices: {
    eyebrow: "Members",
    title: "See what our members say",
    lead: "Different classes and levels. Same club. Here are a few of the people who train with us.",
    items: [
      {
        id: "kristoffer",
        name: "Kristoffer Lundholm",
        sport: "Boxing",
        level: "Advanced",
        src: "/media/kristoffer.mp4",
      },
      {
        id: "holdet",
        name: "From the class",
        sport: "Kickboxing",
        level: "Fitness",
        src: "/media/hero-clip-a.mp4",
      },
      {
        id: "salen",
        name: "In the gym",
        sport: "Kickboxing",
        level: "Advanced",
        src: "/media/voice-hold.mp4",
      },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "Practical questions",
    lead: "The things that are not about fear or the first session. Classes, booking, club kit and reception.",
    groups: [
      {
        id: "hold",
        title: "Classes and levels",
        items: [
          {
            id: "alder",
            q: "What ages train with you?",
            a: "We have classes for children aged 7-10, youth aged 11-17 and adults. If you are 15-17 and sharp and mature enough, the coaches can give junior access so you can also train on the adult classes.",
          },
          {
            id: "niveauer",
            q: "What is the difference between beginner, advanced and fight team?",
            a: "Most people start on the beginner classes and train technique, pads and bags. After you have been going for a while, you can move up to advanced classes. The fight team is for you who want to compete, and promotion happens by agreement with the coach.",
          },
          {
            id: "andre-hold",
            q: "What other classes do you have?",
            a: "Besides the four paths we have Open Gym, where you train on your own, early morning boxing, sparring, wrestling and grappling, and outdoor training when the calendar allows it. The times are in the weekly schedule.",
          },
        ],
      },
      {
        id: "praktisk",
        title: "Practical",
        items: [
          {
            id: "booking",
            q: "How do I book training?",
            a: "You book a spot when you are logged in with a membership. Without login and a fee you cannot reserve a time. The first time you sign up through the first session button.",
          },
          {
            id: "binding",
            q: "Is there a contract, and how do I cancel?",
            a: "There is no contract. If you want to stop, you cancel. You are not tied to a programme you do not want.",
          },
          {
            id: "toj",
            q: "Where do I get club kit and discount codes?",
            a: "As a member you can buy club kit and get discount codes for your own gear. Ask at reception or write to us, and we will help you with the codes.",
          },
          {
            id: "frivillig",
            q: "Can I volunteer?",
            a: "Yes. We always need people who want to help in the gym, at reception or around the classes. Write to us or come by, and we will find a task that fits you.",
          },
          {
            id: "reception",
            q: "When is reception open?",
            a: "Reception is open Monday and Wednesday around 17.15-20.00, when there are classes. Outside those hours you can write to us or drop by when people are training.",
          },
        ],
      },
    ],
  },
  fighter: {
    eyebrow: "Ambition",
    headline: "National team fighters",
    watermark: "NATIONAL",
    body: "Six fighters are selected for the Danish kickboxing national team. Most people start on the beginner classes. The fight team is a choice you make when you are ready.",
    cta: "See the fight team",
    ctaHref: soonHref("kamp"),
    photoCredit: "Photo: Krebs Photo",
    rosterLabel: "The roster",
    titlesLabel: "Titles",
    country: "Denmark",
    pickLabel: "Choose a fighter",
    fighters: [
      {
        id: "charlie",
        image: "/fighters/fighter-04.png",
        name: "Charlie Toma",
        role: "National team A",
        titles: ["Danish champion", "Nordic champion", "King of the Ring", "Danish Open"],
        body: "Charlie has fought MMA, wrestling, kickboxing and muay thai. He is on the A squad, and the titles were won in the ring.",
      },
      {
        id: "dilsa",
        image: "/fighters/fighter-02.png",
        name: "Dilsa Kalan",
        role: "National team B",
        titles: [],
        body: "Dilsa is on the B squad and fights for Aalborg Martial Arts.",
      },
      {
        id: "martin",
        image: "/fighters/fighter-03.png",
        name: "Martin Vemmelund",
        role: "National team A",
        titles: ["King of the Ring", "WBC Muay Thai", "Male fighter of the year 2023"],
        body: "Martin has won King of the Ring in kickboxing and the WBC belt in muay thai. The Danish Kickboxing Federation named him male fighter of the year in 2023.",
      },
      {
        id: "simon",
        image: "/fighters/fighter-05.png",
        name: "Simon Jounan",
        role: "National team A",
        titles: ["2x Danish K1 champion", "Male fighter of the year 2024"],
        body: "Simon has fought both K1 and muay thai. In 2024 the Danish Kickboxing Federation named him male fighter of the year.",
      },
      {
        id: "yousef",
        image: "/fighters/fighter-01.png",
        name: "Yousef Jambali",
        role: "National team B",
        titles: [],
        body: "Yousef is on the B squad. He hits hard and has a background in both K1 and muay thai.",
      },
      {
        id: "salem",
        image: "/fighters/fighter-06.png",
        name: "Salem Salal",
        role: "National team B",
        titles: ["3x Danish champion", "Nordic champion"],
        body: "Salem has a background in kickboxing and boxing and has fought for the club for a long time. He has fought light contact, full contact and K1. Three times Danish champion and once Nordic champion.",
      },
    ],
  },
  findUs: {
    eyebrow: "Nordkraft",
    title: "Find us",
    body: "We train in Nordkraft in the middle of Aalborg. You are welcome to drop by and watch a session, or book your first class. You do not need to have decided anything in advance.",
    reception: "Reception is open Monday and Wednesday around 17.15-20.00, when there are classes.",
    write: "Write to us",
    call: "Call",
    notes: [
      {
        title: "Level 5",
        body: "Enter from Teglgårds Plads or Kjellerups Torv. Take the lift or stairs up.",
      },
      {
        title: "Changing rooms",
        body: "There are changing rooms in the club. Bring training clothes and water. Gear can be borrowed.",
      },
      {
        title: "Reception",
        body: "Monday and Wednesday around 17.15-20.00, when there are classes.",
      },
    ],
  },
  newsTeaser: {
    eyebrow: "The club",
    title: "Club news",
    item: {
      date: "March 2026",
      headline: "Next event and club night",
      body: "Keep an eye here and in the Facebook group for cancellations, events or club nights. When you are logged in, you can book training and see your calendar.",
    },
  },
  schedule: {
    eyebrow: "Times",
    title: "Weekly schedule",
    lead: "Pick a day and see the classes. If this is your first time, start with the button here.",
    cta: "Book first session",
    nextLabel: "Next beginner class",
    emptyToday: "No classes today",
    emptyDay: "No classes on {day}",
    emptyHint: "Pick another day if you want to see the rest of the week.",
    weekdays: {
      mon: "Monday",
      tue: "Tuesday",
      wed: "Wednesday",
      thu: "Thursday",
      fri: "Friday",
      sat: "Saturday",
      sun: "Sunday",
    },
    weekdaysShort: {
      mon: "Mon",
      tue: "Tue",
      wed: "Wed",
      thu: "Thu",
      fri: "Fri",
      sat: "Sat",
      sun: "Sun",
    },
    classes: {
      "kids-7-10": "Kids 7-10",
      "kick-thai-beginner": "Kick / Thai beginner",
      "kick-thai-advanced": "Kick / Thai advanced",
      "boxing-beginner": "Boxing beginner",
      fight: "Fight team",
      kicknburn: "Kick'n Burn",
      "open-gym": "Open gym",
    },
    spots: {
      open: "Open",
      few: "Few spots",
    },
  },
  sponsors: {
    eyebrow: "Partnership",
    title: "Our partners",
    lead: "They help keep training and everyday life in Nordkraft going.",
    thanks: "Thank you for being with us.",
    cta: "Become a sponsor",
    ctaHref: soonHref("sponsorer"),
    write: "Write to us",
    items: [
      {
        name: "OK",
        href: "https://www.ok.dk/lokalsporten",
        logo: "/sponsors/ok.png",
        body: "Every time you fill up at OK, you can support the club. It costs you nothing extra. OK pays the amount.",
      },
      {
        name: "Axon",
        href: "https://www.axonprofil.dk",
        logo: "/sponsors/axon.png",
        body: "Axon makes promotional products with a logo. Bottles, t-shirts and what a club or company needs.",
      },
      {
        name: "Igniz",
        href: "https://igniz.dk",
        logo: "/sponsors/igniz.jpg",
        body: "Igniz are certified fire safety advisors. They advise on building projects, from housing to culture, schools and hospitals.",
      },
      {
        name: "Portservice Nord",
        href: soonHref("portservice"),
        logo: "/sponsors/portservice-nord.png",
        body: "Portservice Nord sells, installs and services doors for homes and businesses. They are based in Ellidshøj.",
      },
    ],
  },
} satisfies typeof da;
